### ISSUE TITLE
panic: rename [temp location] [dest]: invalid cross-device link

### ISSUE THREAD

**Issue by flenter** [wercker/mhook#12]
This problem has been recently introduced, a build from december (commit 977de34db80e88f0981d9289ff6f3ad7fee8640d) didn't have this issue.

**Comment by mwhooker** [comment]
how do you reproduce this?:
where did you see it?
what version of mhook were you using?
is there a stack trace?

**Comment by mwhooker** [comment]
I can reproduce.

- [ ] make target directory if it doesn't exist

**Comment by mwhooker** [comment]
It's because it's trying to move the file across partitions

https://groups.google.com/forum/#!topic/golang-dev/5w7Jmg_iCJQ
